FEATURES_REQUIRED += cpp
USEMODULE += cpp11-compat

USEPKG += flatbuffers
USEPKG += gemmlowp

USEMODULE += tensorflow-lite
USEMODULE += tensorflow-lite-c
USEMODULE += tensorflow-lite-core
USEMODULE += tensorflow-lite-exp-micro-kernels
USEMODULE += tensorflow-lite-kernels
USEMODULE += tensorflow-lite-kernels-internal
USEMODULE += tensorflow-lite-memory

ifneq (,$(filter tensorflow-lite-magic_wand,$(USEMODULE)))
  USEMODULE += lsm6dsl
endif
