FEATURES_REQUIRED += periph_spi
FEATURES_REQUIRED += periph_gpio
USEMODULE += ztimer_msec
ifneq (,$(filter periph_rtt,$(USEMODULE)))
  USEMODULE += ztimer_periph_rtt
else
  USEMODULE += ztimer_usec
endif
