PKG_NAME=zlib-deflate-nostdlib
PKG_URL=https://github.com/derf/zlib-deflate-nostdlib
PKG_VERSION=8198be8fb6f81e987c3d0a2f334f61914f77c84b
PKG_LICENSE=BSD

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)/src -f $(CURDIR)/$(PKG_NAME).mk
