CPU_CORE = cortex-m0
CPU_FAM  = scum

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_gpio
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_timer_query_freqs
FEATURES_PROVIDED += periph_uart

include $(RIOTCPU)/cortexm_common/Makefile.features
