FEATURES_REQUIRED += periph_gpio_irq
FEATURES_REQUIRED += periph_i2c
USEMODULE += ztimer_msec
ifneq (,$(filter periph_rtt,$(USEMODULE)))
  USEMODULE += ztimer_periph_rtt
else
  USEMODULE += ztimer_usec
endif
