ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += stm32_eth
endif

ifneq (,$(filter touch_dev,$(USEMODULE)))
  USEMODULE += ft5336
endif
