name: static-test

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run static test
      uses: aabadie/riot-actions@master
      with:
        cmd: make static-test
