name: tools-test

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        directory:
          - dist/tools/backport_pr
          - dist/tools/compile_and_test_for_board
          - dist/pythonlibs/riotctrl_shell
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox pytest-github-actions-annotate-failures
        python -m pip install kconfiglib
    - name: Test ${{ matrix.directory }}
      run: cd ${{ matrix.directory }} && tox
  kconfiglib-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install kconfiglib
    - name: Test kconfig script
      run: cd dist/tools/kconfiglib/tests && ./test.sh
